# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

dotenv: [".env"]

vars:
  EXECUTABLE: videotagger

tasks:
  build:
    deps: [vet]
    cmds:
      - go build -v -ldflags="-X main.Version={{.VERSION}}" -o {{.EXECUTABLE}} main.go
    sources:
      - ./*.go
    generates:
      - "{{.EXECUTABLE}}"
    vars:
      VERSION:
        sh: |
          tag=$(git describe --tags 2>/dev/null || echo "dev")
          commit=$(git log -n 1 --format=%h)
          if [ "$tag" = "dev" ]; then
            echo "dev-$commit"
          else
            echo "$tag-$commit"
          fi

  vet:
    cmds:
      - go vet ./...
    sources:
      - ./*.go
  publish:
    deps: [build]
    cmds:
      - echo "Publishing to bin"
      - mkdir -p $HOME/bin/
      - mv {{.EXECUTABLE}} $HOME/bin/

  lint:
    desc: Run Go linters
    cmds:
      - golangci-lint run ./...
    sources:
      - ./**/*.go
    silent: true

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILDDIR}} {{.COVERAGE_DIR}}

  upgrade-deps:
    desc: Upgrade all dependencies to their latest versions
    silent: true
    cmds:
      - go get -u ./...
      - go mod tidy
      - echo "✅ Dependencies upgraded successfully"
    sources:
      - go.mod
      - go.sum
    generates:
      - go.mod
      - go.sum
