// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAutoSelect(arg1, arg2) {
  return window['go']['main']['App']['ApplyAutoSelect'](arg1, arg2);
}

export function ClearSelectionInGroup(arg1) {
  return window['go']['main']['App']['ClearSelectionInGroup'](arg1);
}

export function ConfirmDeleteSelected(arg1) {
  return window['go']['main']['App']['ConfirmDeleteSelected'](arg1);
}

export function DeleteSelected() {
  return window['go']['main']['App']['DeleteSelected']();
}

export function GetPreview(arg1) {
  return window['go']['main']['App']['GetPreview'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function SelectAllInGroup(arg1) {
  return window['go']['main']['App']['SelectAllInGroup'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ToggleSelection(arg1, arg2) {
  return window['go']['main']['App']['ToggleSelection'](arg1, arg2);
}
