// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyAutoSelect(arg1:number,arg2:number):Promise<main.AppState>;

export function ClearSelectionInGroup(arg1:number):Promise<main.AppState>;

export function DeleteSelected():Promise<main.AppState>;

export function GetPreview(arg1:string):Promise<main.Preview>;

export function GetState():Promise<main.AppState>;

export function ScanDirectory(arg1:string):Promise<main.AppState>;

export function SelectAllInGroup(arg1:number):Promise<main.AppState>;

export function SelectDirectory():Promise<string>;

export function ToggleSelection(arg1:number,arg2:number):Promise<main.AppState>;
