---
name: Go CI

'on':
  push:
    branches: [main, feature/kong-phash]
  pull_request:
    branches: [main, feature/kong-phash]
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        # v5.2.0
        with:
          go-version: "1.24"
          cache: true  # Automatically caches go.mod/go.sum dependencies

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
        # v2.0.0
        with:
          version: 3.x

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Go tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Run tests with coverage
        run: task test-ci

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        # v5.2.0
        with:
          go-version: "1.24"
          cache: true

      - name: golangci-lint
        # v6.1.0
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86
        with:
          version: latest
          args: --timeout=5m

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        # v5.2.0
        with:
          go-version: "1.24"
          cache: true

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
        # v2.0.0
        with:
          version: 3.x

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Build
        run: task build

      - name: Create nightly tag
        if: github.event_name == 'schedule'
        run: |
          NIGHTLY_TAG="nightly-$(date +%Y-%m-%d)"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "$NIGHTLY_TAG" -m "Nightly build for $(date +%Y-%m-%d)"
          git push origin "$NIGHTLY_TAG"

      - name: Cleanup old nightly tags
        if: github.event_name == 'schedule'
        run: |
          # Keep last 30 days of nightly tags
          CUTOFF_DATE=$(date -d '30 days ago' +%Y-%m-%d)
          git fetch --tags
          for tag in $(git tag -l "nightly-*" | sort); do
            tag_date=$(echo "$tag" | sed 's/nightly-//')
            if [[ "$tag_date" < "$CUTOFF_DATE" ]]; then
              echo "Removing old nightly tag: $tag"
              git push --delete origin "$tag" || true
            fi
          done

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@6d798873df2b1b8e5846dba6fb86631229fbcb17
        # v4.6.0
        if: success() && hashFiles('./coverage.out') != ''
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
