name: Go CI

on:
  push:
    branches: [main, feature/kong-phash]
  pull_request:
    branches: [main, feature/kong-phash]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Install Go tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run build-ci
        run: task build-ci

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: success()
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella